# Generated by Django 5.0.2 on 2024-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasEncadenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=20)),
                ('p1', models.CharField(max_length=20)),
                ('p2', models.CharField(max_length=20)),
                ('p3', models.CharField(max_length=20)),
                ('p4', models.CharField(max_length=20)),
                ('p5', models.CharField(max_length=20)),
                ('p6', models.CharField(max_length=20)),
            ],
        ),
    ]
