# Generated by Django 5.0.2 on 2024-02-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReCAI_APP', '0002_alter_palabrasencadenadas_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='EslabonCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=20)),
                ('p2', models.CharField(max_length=20)),
                ('p3', models.CharField(max_length=20)),
                ('p4', models.CharField(max_length=20)),
                ('p5', models.CharField(max_length=20)),
                ('p6', models.CharField(max_length=20)),
                ('p7', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RondaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=20)),
                ('p2', models.CharField(max_length=20)),
                ('p3', models.CharField(max_length=20)),
                ('p4', models.CharField(max_length=20)),
                ('p5', models.CharField(max_length=20)),
                ('p6', models.CharField(max_length=20)),
                ('p7', models.CharField(max_length=20)),
                ('p8', models.CharField(max_length=20)),
                ('p9', models.CharField(max_length=20)),
                ('p10', models.CharField(max_length=20)),
                ('p11', models.CharField(max_length=20)),
                ('p12', models.CharField(max_length=20)),
                ('p13', models.CharField(max_length=20)),
                ('final', models.CharField(max_length=20)),
                ('pista', models.CharField(max_length=20)),
            ],
        ),
    ]
