# Generated by Django 5.0.2 on 2024-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReCAI_APP', '0003_eslaboncentral_rondafinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
    ]
